// backend/mockLeague.js

const mockLeague = {
  leagueKey: 'mock.league.2024',
  name: "Mock Version of Jack's Yahoo League",
  season: '2024',
  teams: [
    {
      teamId: 1,
      name: "Jack's Mock Team", 
      manager: 'Jack',
      roster: [
        { playerId: 1, name: 'Joe Burrow', position: 'QB', team: 'CIN', value: 0 },
        { playerId: 2, name: 'Saquon Barkley', position: 'RB', team: 'PHI', value: 0 },
        { playerId: 3, name: 'Josh Jacobs', position: 'RB', team: 'GB', value: 0 },
        { playerId: 4, name: 'A.J. Brown', position: 'WR', team: 'PHI', value: 0 },
        { playerId: 5, name: 'Chris Olave', position: 'WR', team: 'NO', value: 0 },
        { playerId: 6, name: 'T.J. Hockenson', position: 'TE', team: 'MIN', value: 0 },
        { playerId: 7, name: 'Jaylen Warren', position: 'RB', team: 'PIT', value: 0 },
        { playerId: 8, name: 'Broncos D/ST', position: 'DST', team: 'DEN', value: 0 },
        { playerId: 9, name: 'Andy Borregales', position: 'K', team: 'NE', value: 0 },
        { playerId: 10, name: 'Terry McLaurin', position: 'WR', team: 'WSH', value: 0 },
        { playerId: 11, name: 'Khalil Shakir', position: 'WR', team: 'BUF', value: 0 },
        { playerId: 12, name: 'Jauan Jennings', position: 'WR', team: 'SF', value: 0 },
        { playerId: 13, name: 'Caleb Williams', position: 'QB', team: 'CHI', value: 0 },
        { playerId: 14, name: 'C.J. Stroud', position: 'QB', team: 'HOU', value: 0 },
        { playerId: 15, name: 'Lions D/ST', position: 'DST', team: 'DET', value: 0 },
        { playerId: 16, name: 'Kareem Hunt', position: 'RB', team: 'KC', value: 0 },
      ],
    },
    {
      teamId: 2,
      name: 'Mock Team 2',
      manager: 'Friend 1',
      roster: [
        { playerId: 17, name: 'Josh Allen', position: 'QB', team: 'BUF', value: 0 },
        { playerId: 18, name: "De'Von Achane", position: 'RB', team: 'MIA', value: 0 },
        { playerId: 19, name: 'Zach Charbonnet', position: 'RB', team: 'SEA', value: 0 },
        { playerId: 20, name: 'Puka Nacua', position: 'WR', team: 'LAR', value: 0 },
        { playerId: 21, name: 'Jaxon Smith-Njigba', position: 'WR', team: 'SEA', value: 0 },
        { playerId: 22, name: 'Travis Kelce', position: 'TE', team: 'KC', value: 0 },
        { playerId: 23, name: 'Michael Pittman Jr.', position: 'WR', team: 'IND', value: 0 },
        { playerId: 24, name: 'Jaguars D/ST', position: 'DST', team: 'JAX', value: 0 },
        { playerId: 25, name: 'Cairo Santos', position: 'K', team: 'CHI', value: 0 },
        { playerId: 26, name: 'Courtland Sutton', position: 'WR', team: 'DEN', value: 0 },
        { playerId: 27, name: 'Rhamondre Stevenson', position: 'RB', team: 'NE', value: 0 },
        { playerId: 28, name: 'Jordan Addison', position: 'WR', team: 'MIN', value: 0 },
        { playerId: 29, name: 'Rashid Shaheed', position: 'WR', team: 'SEA', value: 0 },
        { playerId: 30, name: 'Daniel Jones', position: 'QB', team: 'IND', value: 0 },
        { playerId: 31, name: 'Romeo Doubs', position: 'WR', team: 'GB', value: 0 },
        { playerId: 32, name: 'Hunter Henry', position: 'TE', team: 'NE', value: 0 },
      ],
    },
    {
      teamId: 3,
      name: 'Mock Team 3',
      manager: 'Friend 2',
      roster: [
        { playerId: 33, name: 'Jalen Hurts', position: 'QB', team: 'PHI', value: 0 },
        { playerId: 34, name: 'Bijan Robinson', position: 'RB', team: 'ATL', value: 0 },
        { playerId: 35, name: 'Kyren Williams', position: 'RB', team: 'LAR', value: 0 },
        { playerId: 36, name: 'Ladd McConkey', position: 'WR', team: 'LAC', value: 0 },
        { playerId: 37, name: 'Emeka Egbuka', position: 'WR', team: 'TB', value: 0 },
        { playerId: 38, name: 'Dalton Kincaid', position: 'TE', team: 'BUF', value: 0 },
        { playerId: 39, name: 'Xavier Worthy', position: 'WR', team: 'KC', value: 0 },
        { playerId: 40, name: 'Bills D/ST', position: 'DST', team: 'BUF', value: 0 },
        { playerId: 41, name: 'Chris Boswell', position: 'K', team: 'PIT', value: 0 },
        { playerId: 42, name: 'George Kittle', position: 'TE', team: 'SF', value: 0 },
        { playerId: 43, name: 'Joe Mixon', position: 'RB', team: 'HOU', value: 0 },
        { playerId: 44, name: 'Tony Pollard', position: 'RB', team: 'TEN', value: 0 },
        { playerId: 45, name: "Wan'Dale Robinson", position: 'WR', team: 'NYG', value: 0 },
        { playerId: 46, name: 'Keon Coleman', position: 'WR', team: 'BUF', value: 0 },
        { playerId: 47, name: 'Matthew Stafford', position: 'QB', team: 'LAR', value: 0 },
        { playerId: 48, name: 'Isiah Pacheco', position: 'RB', team: 'KC', value: 0 },
      ],
    },
    {
      teamId: 4,
      name: 'Mock Team 4',
      manager: 'Friend 3',
      roster: [
        { playerId: 49, name: 'Drake Maye', position: 'QB', team: 'NE', value: 0 },
        { playerId: 50, name: 'Jahmyr Gibbs', position: 'RB', team: 'DET', value: 0 },
        { playerId: 51, name: 'Breece Hall', position: 'RB', team: 'NYJ', value: 0 },
        { playerId: 52, name: 'George Pickens', position: 'WR', team: 'DAL', value: 0 },
        { playerId: 53, name: 'Michael Wilson', position: 'WR', team: 'ARI', value: 0 },
        { playerId: 54, name: 'Oronde Gadsden II', position: 'TE', team: 'LAC', value: 0 },
        { playerId: 55, name: 'Chase Brown', position: 'RB', team: 'CIN', value: 0 },
        { playerId: 56, name: 'Falcons D/ST', position: 'DST', team: 'ATL', value: 0 },
        { playerId: 57, name: 'Jason Myers', position: 'K', team: 'SEA', value: 0 },
        { playerId: 58, name: 'Drake London', position: 'WR', team: 'ATL', value: 0 },
        { playerId: 59, name: 'Marvin Harrison Jr.', position: 'WR', team: 'ARI', value: 0 },
        { playerId: 60, name: 'Tetairoa McMillan', position: 'WR', team: 'CAR', value: 0 },
        { playerId: 61, name: 'TreVeyon Henderson', position: 'RB', team: 'NE', value: 0 },
        { playerId: 62, name: 'Devin Neal', position: 'RB', team: 'NO', value: 0 },
        { playerId: 63, name: 'Jayden Higgins', position: 'WR', team: 'HOU', value: 0 },
        { playerId: 64, name: 'Theo Johnson', position: 'TE', team: 'NYG', value: 0 },
        { playerId: 65, name: 'Brandon Aiyuk', position: 'WR', team: 'SF', value: 0 },
      ],
    },
    {
      teamId: 5,
      name: 'Mock Team 5',
      manager: 'Friend 4',
      roster: [
        { playerId: 66, name: 'Justin Herbert', position: 'QB', team: 'LAC', value: 0 },
        { playerId: 67, name: 'Christian McCaffrey', position: 'RB', team: 'SF', value: 0 },
        { playerId: 68, name: 'Derrick Henry', position: 'RB', team: 'BAL', value: 0 },
        { playerId: 69, name: 'Jaylen Waddle', position: 'WR', team: 'MIA', value: 0 },
        { playerId: 70, name: 'Deebo Samuel', position: 'WR', team: 'WSH', value: 0 },
        { playerId: 71, name: 'David Njoku', position: 'TE', team: 'CLE', value: 0 },
        { playerId: 72, name: 'James Cook III', position: 'RB', team: 'BUF', value: 0 },
        { playerId: 73, name: 'Giants D/ST', position: 'DST', team: 'NYG', value: 0 },
        { playerId: 74, name: 'Chase McLaughlin', position: 'K', team: 'TB', value: 0 },
        { playerId: 75, name: 'Garrett Wilson', position: 'WR', team: 'NYJ', value: 0 },
        { playerId: 76, name: 'DJ Moore', position: 'WR', team: 'CHI', value: 0 },
        { playerId: 77, name: 'Cooper Kupp', position: 'WR', team: 'SEA', value: 0 },
        { playerId: 78, name: 'Quinshon Judkins', position: 'RB', team: 'CLE', value: 0 },
        { playerId: 79, name: 'Jerome Ford', position: 'RB', team: 'CLE', value: 0 },
        { playerId: 80, name: 'Jordan Love', position: 'QB', team: 'GB', value: 0 },
        { playerId: 81, name: 'Sam LaPorta', position: 'TE', team: 'DET', value: 0 },
      ],
    },
    {
      teamId: 6,
      name: 'Mock Team 6',
      manager: 'Friend 5',
      roster: [
        { playerId: 82, name: 'Patrick Mahomes', position: 'QB', team: 'KC', value: 0 },
        { playerId: 83, name: 'Bucky Irving', position: 'RB', team: 'TB', value: 0 },
        { playerId: 84, name: 'Travis Etienne Jr.', position: 'RB', team: 'JAX', value: 0 },
        { playerId: 85, name: "Ja'Marr Chase", position: 'WR', team: 'CIN', value: 0 },
        { playerId: 86, name: 'Rashee Rice', position: 'WR', team: 'KC', value: 0 },
        { playerId: 87, name: 'Brock Bowers', position: 'TE', team: 'LV', value: 0 },
        { playerId: 88, name: 'Stefon Diggs', position: 'WR', team: 'NE', value: 0 },
        { playerId: 89, name: 'Rams D/ST', position: 'DST', team: 'LAR', value: 0 },
        { playerId: 90, name: 'Jake Bates', position: 'K', team: 'DET', value: 0 },
        { playerId: 91, name: 'Alvin Kamara', position: 'RB', team: 'NO', value: 0 },
        { playerId: 92, name: 'Baker Mayfield', position: 'QB', team: 'TB', value: 0 },
        { playerId: 93, name: 'Jacory Croskey-Merritt', position: 'RB', team: 'WSH', value: 0 },
        { playerId: 94, name: 'Zach Ertz', position: 'TE', team: 'WSH', value: 0 },
        { playerId: 95, name: 'Tyrone Tracy Jr.', position: 'RB', team: 'NYG', value: 0 },
        { playerId: 96, name: 'Parker Washington', position: 'WR', team: 'JAX', value: 0 },
        { playerId: 97, name: 'Steelers D/ST', position: 'DST', team: 'PIT', value: 0 },
        { playerId: 98, name: 'Mike Evans', position: 'WR', team: 'TB', value: 0 },
      ],
    },
    {
      teamId: 7,
      name: 'Mock Team 7',
      manager: 'Friend 6',
      roster: [
        { playerId: 99, name: 'Jaxson Dart', position: 'QB', team: 'NYG', value: 0 },
        { playerId: 100, name: 'Jonathan Taylor', position: 'RB', team: 'IND', value: 0 },
        { playerId: 101, name: 'David Montgomery', position: 'RB', team: 'DET', value: 0 },
        { playerId: 102, name: 'Justin Jefferson', position: 'WR', team: 'MIN', value: 0 },
        { playerId: 103, name: 'DeVonta Smith', position: 'WR', team: 'PHI', value: 0 },
        { playerId: 104, name: 'Tyler Warren', position: 'TE', team: 'IND', value: 0 },
        { playerId: 105, name: 'CeeDee Lamb', position: 'WR', team: 'DAL', value: 0 },
        { playerId: 106, name: 'Chargers D/ST', position: 'DST', team: 'LAC', value: 0 },
        { playerId: 107, name: 'Cam Little', position: 'K', team: 'JAX', value: 0 },
        { playerId: 108, name: 'Tee Higgins', position: 'WR', team: 'CIN', value: 0 },
        { playerId: 109, name: 'Jayden Daniels', position: 'QB', team: 'WSH', value: 0 },
        { playerId: 110, name: 'Mark Andrews', position: 'TE', team: 'BAL', value: 0 },
        { playerId: 111, name: 'Rachaad White', position: 'RB', team: 'TB', value: 0 },
        { playerId: 112, name: 'Quentin Johnston', position: 'WR', team: 'LAC', value: 0 },
        { playerId: 113, name: 'Jerry Jeudy', position: 'WR', team: 'CLE', value: 0 },
        { playerId: 114, name: 'Sam Darnold', position: 'QB', team: 'SEA', value: 0 },
      ],
    },
    {
      teamId: 8,
      name: 'Mock Team 8',
      manager: 'Friend 7',
      roster: [
        { playerId: 115, name: 'Dak Prescott', position: 'QB', team: 'DAL', value: 0 },
        { playerId: 116, name: 'Omarion Hampton', position: 'RB', team: 'LAC', value: 0 },
        { playerId: 117, name: 'Kenneth Gainwell', position: 'RB', team: 'PIT', value: 0 },
        { playerId: 118, name: 'Brian Thomas Jr.', position: 'WR', team: 'JAX', value: 0 },
        { playerId: 119, name: 'Rome Odunze', position: 'WR', team: 'CHI', value: 0 },
        { playerId: 120, name: 'Trey McBride', position: 'TE', team: 'ARI', value: 0 },
        { playerId: 121, name: 'Jameson Williams', position: 'WR', team: 'DET', value: 0 },
        { playerId: 122, name: 'Seahawks D/ST', position: 'DST', team: 'SEA', value: 0 },
        { playerId: 123, name: 'Cameron Dicker', position: 'K', team: 'LAC', value: 0 },
        { playerId: 124, name: 'Ricky Pearsall', position: 'WR', team: 'SF', value: 0 },
        { playerId: 125, name: 'Trey Benson', position: 'RB', team: 'ARI', value: 0 },
        { playerId: 126, name: 'Tyler Allgeier', position: 'RB', team: 'ATL', value: 0 },
        { playerId: 127, name: 'Tre Tucker', position: 'WR', team: 'LV', value: 0 },
        { playerId: 128, name: 'Josh Downs', position: 'WR', team: 'IND', value: 0 },
        { playerId: 129, name: 'Emanuel Wilson', position: 'RB', team: 'GB', value: 0 },
        { playerId: 130, name: 'Jared Goff', position: 'QB', team: 'DET', value: 0 },
      ],
    },
    {
      teamId: 9,
      name: 'Mock Team 9',
      manager: 'Friend 8',
      roster: [
        { playerId: 131, name: 'Bo Nix', position: 'QB', team: 'DEN', value: 0 },
        { playerId: 132, name: 'RJ Harvey', position: 'RB', team: 'DEN', value: 0 },
        { playerId: 133, name: 'Rico Dowdle', position: 'RB', team: 'CAR', value: 0 },
        { playerId: 134, name: 'Nico Collins', position: 'WR', team: 'HOU', value: 0 },
        { playerId: 135, name: 'Davante Adams', position: 'WR', team: 'LAR', value: 0 },
        { playerId: 136, name: 'Jake Ferguson', position: 'TE', team: 'DAL', value: 0 },
        { playerId: 137, name: 'Kenneth Walker III', position: 'RB', team: 'SEA', value: 0 },
        { playerId: 138, name: 'Texans D/ST', position: 'DST', team: 'HOU', value: 0 },
        { playerId: 139, name: 'Brandon Aubrey', position: 'K', team: 'DAL', value: 0 },
        { playerId: 140, name: "D'Andre Swift", position: 'RB', team: 'CHI', value: 0 },
        { playerId: 141, name: 'Jordan Mason', position: 'RB', team: 'MIN', value: 0 },
        { playerId: 142, name: 'Keenan Allen', position: 'WR', team: 'LAC', value: 0 },
        { playerId: 143, name: 'Troy Franklin', position: 'WR', team: 'DEN', value: 0 },
        { playerId: 144, name: 'Kyle Monangai', position: 'RB', team: 'CHI', value: 0 },
        { playerId: 145, name: 'Sean Tucker', position: 'RB', team: 'TB', value: 0 },
        { playerId: 146, name: 'Brock Purdy', position: 'QB', team: 'SF', value: 0 },
      ],
    },
    {
      teamId: 10,
      name: 'Mock Team 10',
      manager: 'Friend 9',
      roster: [
        { playerId: 147, name: 'Lamar Jackson', position: 'QB', team: 'BAL', value: 0 },
        { playerId: 148, name: 'Ashton Jeanty', position: 'RB', team: 'LV', value: 0 },
        { playerId: 149, name: 'Javonte Williams', position: 'RB', team: 'DAL', value: 0 },
        { playerId: 150, name: 'DK Metcalf', position: 'WR', team: 'PIT', value: 0 },
        { playerId: 151, name: 'Zay Flowers', position: 'WR', team: 'BAL', value: 0 },
        { playerId: 152, name: 'Dallas Goedert', position: 'TE', team: 'PHI', value: 0 },
        { playerId: 153, name: 'Aaron Jones Sr.', position: 'RB', team: 'MIN', value: 0 },
        { playerId: 154, name: 'Patriots D/ST', position: 'DST', team: 'NE', value: 0 },
        { playerId: 155, name: "Ka'imi Fairbairn", position: 'K', team: 'HOU', value: 0 },
        { playerId: 156, name: 'Amon-Ra St. Brown', position: 'WR', team: 'DET', value: 0 },
        { playerId: 157, name: 'Chuba Hubbard', position: 'RB', team: 'CAR', value: 0 },
        { playerId: 158, name: 'Jakobi Meyers', position: 'WR', team: 'JAX', value: 0 },
        { playerId: 159, name: 'Chris Godwin Jr.', position: 'WR', team: 'TB', value: 0 },
        { playerId: 160, name: 'Woody Marks', position: 'RB', team: 'HOU', value: 0 },
        { playerId: 161, name: 'Kimani Vidal', position: 'RB', team: 'LAC', value: 0 },
        { playerId: 162, name: 'Ravens D/ST', position: 'DST', team: 'BAL', value: 0 },
      ],
    },
  ],
};

module.exports = mockLeague;